### ISSUE TITLE
Build fails on windows 7 64-bit, building for 64-bit

### ISSUE THREAD

**Issue by HenryHRich** [iocane/unbox#14]
Running tup on windows7 64-bit.
All compiles complete OK.
First LINK (for libj) fails with message
src\libj\win\winasm64.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'

**Comment by iocane** [comment]
Are you sure you opened the 64 bit visual studio console?

**Comment by mlochbaum** [comment]
Resolved outside of Github. For those with the same issue, here's the fix:

From the start menu, run Visual Studio tools, which opens a folder with a bunch of console shortcuts. Run tup using the "64 bit native" console.
