### ISSUE TITLE
E. fails on integer input containing _1

### ISSUE THREAD

**Issue by mlochbaum** [iocane/unbox#4]
The following line returns all zeros even though the left argument is contained in the right:

```
_2 1  E.  1 2 _1 _2 1
```

This is the case whenever a `_1` appears in the right argument to `E.` before the left argument does.

**Comment by iocane** [comment]
This appears to be a bug in special code to handle small range values. This works:
`_18 1  E.  1 2 _1 _18 1`
I'm inclined to remove the special code for the time being unless someone provides a patch. I think it should be profiled as well to see how much benefit it provides.

**Comment by iocane** [comment]
There is a fix for this in the latest develop commit. I'm leaving the issue open for now pending further testing/validation.

**Comment by iocane** [comment]
Fixed in v0.1-rc1.
