### ISSUE TITLE
Segmentation fault on some gerund arguments to ^:

### ISSUE THREAD

**Issue by mlochbaum** [iocane/unbox#5]
Executing the following yields a segfault with any string in place of `'string'`:

```
]^:(1:`(<,'0';'string')) 0
```

**Comment by iocane** [comment]
Another missing type test when recovering the verbs from a gerund. The curious thing about this one is that I could not find any test coverage for ^: with gerund right arguments. Fixed in commit 41c629ff83d3f0e91f51c9ba386cd77ade1e8934.
