### ISSUE TITLE
No tup entry for config/macosx

### ISSUE THREAD

**Issue by hoosierEE** [iocane/unbox#8]
System is: Mac OSX 10.11.2

Note that I installed tup via Homebrew, which required two steps due to some kext permission thing:

```
$ brew install Caskroom/cask/osxfuse
$ brew install homebrew/fuse/tup
```

Here is the full output:

```
$ tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.003s] Reading in new environment variables...
[ tup ] [0.003s] Parsing Tupfiles...
* 1) [0.002s] .
tup error: Unable to find tup entry for file 'config/macosx'
tup error: Failed to parse included file 'config/macosx'
tup error: Error parsing Tupfile line 16
  Line was: 'include config/@(TUP_PLATFORM)'
 [     ETA~=<1s      ]   5%
 *** tup: 1 job failed.
```

Tried on the develop branch to be thorough; same error:

```
$ git checkout develop
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
$ tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.024s] Reading in new configuration/environment variables...
 1) updated variant: tup.config
 [ ] 100%
[ tup ] [0.027s] Parsing Tupfiles...                                                                                   
* 1) [0.002s] .
tup error: Unable to find tup entry for file 'config/macosx'
tup error: Failed to parse included file 'config/macosx'
tup error: Error parsing Tupfile line 16
  Line was: 'include config/@(TUP_PLATFORM)'
 [     ETA~=<1s      ]   5%
 *** tup: 1 job failed.
$ 
```

**Comment by hoosierEE** [comment]
Ah well I now have a very rudimentary understanding of Tup and this error is simply saying that we haven't yet made a config/macosx file for Tup to read.

**Comment by iocane** [comment]
That's right, we need to make a config/macosx file. I imagine it should be very similar to the linux file. If you want to try it out, copy the linux file, then I can help you fix any issues if you paste the output here.

**Comment by hoosierEE** [comment]
Maybe making progress, not sure yet.

Merely changing the `*.so` into `*.dylib` is not sufficient to produce a working executable on OSX.

One issue I noticed so far:

In the file `hostdefs.sym` the line `<pcreposix.h>` should be `"pcreposix.h"` because it's a local include.  This requires a change to `sym2ijs.ijs` because it's currently only looking for header files wrapped in angle brackets `<likethis.h>`.

I'll give it a go tomorrow if I have time.

**Comment by iocane** [comment]
I had the same problem with the sym2ijs script. Instead of changing it, I just added -an I option to gcc to tell it to search for headers in that directory. Maybe it's not being picked up properly or is more strict on Mac. Which compiler are you using?

**Comment by hoosierEE** [comment]
I have both clang and gcc on that system so I'm not 100% sure, but the Tupfile tests for the presence of clang first so probably clang.  Will test tomorrow.

**Comment by iocane** [comment]
Actually, after looking again I see that I did _not_ add -Isrc/libj/defs to the compile command. I don't know why it works in Linux but the OSX compiler probably treats it differently than gcc on Linux. Try this when you get a chance: change this

`: foreach $(defdir)/*.c |> ^ CC %f^ $(CC) %f -o %o |> bin/%B {defs}`

to:

`: foreach $(defdir)/*.c |> ^ CC %f^ $(CC) -Isrc/libj/defs %f -o %o |> bin/%B {defs}`
